### ISSUE TITLE
ES6 features preventing use of Node.js v0.10 or v0.12

### ISSUE THREAD

**Issue by svennam92** [Rcomian/bunyan-rotating-file-stream#3]
Short discussion here:
https://gitter.im/Rcomian/bunyan-rotating-file-stream

SyntaxError: Use of const in strict mode.
at /Users/svennam/git-apim/apiconnect-cli-logger/node_modules/bunyan-rotating-file-stream/lib/rotatingfilestream.js:23

**Comment by Rcomian** [comment]
Am making progress on this issue. Officially supported node versions will be:

* 0.12.9
* 0.12.latest (0.12.11 now)
* 4.latest (4.3.2)
* 5.latest (5.7.1)

Other versions when requested.

0.10 was absent a lot of useful path manipulation logic which I'm not to patch in with packages. Unless explicitly requested I'm not going to support node 0.10 or earlier.

Other issues found: 

* Prior to node 5 there is a bug where `setImmediate` may never fire.
* Node 0.12 cannot handle the load produced by the tests and misses timer events. Since in real life the process should be allowed to breath and process these events I've slowed the writes when running the tests in node 0.12. However this means the tests took too long, so I've also reduced the workload size for the tests.
* On shared streams I was still creating multiple triggers which caused issues on node <5
* `mkdir-recursive` does not work at all on 0.10, I've moved to `mkdirp` even though 0.10 isn't supported for other reasons.

I'm going to go with 1 compatible codebase at the moment.
Some ES6 does provide nice syntactic sugar though (destructuring, non duplicate names in revealing modules pattern, arrow functions), so in the future may consider transpiling a compatible version for older node versions.

Test run times:

* 0.12 ~ 58s
* 4 ~ 22s
* 5 ~ 20s

**Comment by Rcomian** [comment]
I've release version 1.5.2 of the rotating file stream.

This release marks defined compatibility with a set of node versions with tests against each of those versions. Further issues with those versions should be raised separately, but this issue should be completed.
